name: amarelinha-js-server

services:
  pg:
    image: bitnami/postgresql:17.0.0
    ports:
      - '5434:5434'
    environment:
      - POSTGRES_USER=docker-amarelinha
      - POSTGRES_PASSWORD=dockeramarelinha
      - POSTGRES_DB=amarelinha